#!/bin/bash
set -e

for tag in {qt,kde-frameworks,kde-plasma}; do
  docker build --target "$tag" -f "$DOCKERFILE_PATH" -t "${DOCKER_REPO}:${tag}" .
done

docker tag "${DOCKER_REPO}:kde-frameworks" "${DOCKER_REPO}:latest"